FROM mcr.microsoft.com/dotnet/core/runtime:3.1

#####################
#PUPPETEER RECIPE
#####################
# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
ARG CHROME_VERSION="81.0.4044.138-1"
RUN apt-get update && apt-get -f install && apt-get -y install wget gnupg2 apt-utils
RUN wget --no-verbose -O /tmp/chrome.deb http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
&& apt-get update \
&& apt-get install -y /tmp/chrome.deb --no-install-recommends --allow-downgrades fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
&& rm /tmp/chrome.deb

RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser


WORKDIR /home/app
COPY bin/Release/netcoreapp3.1/publish .

RUN ls -la


CMD ["ls","-la"]
RUN ls -la
RUN chown -R pptruser /home/*
USER pptruser
ENV PUPPETEER_EXECUTABLE_PATH "/usr/bin/google-chrome"
RUN whoami
ENTRYPOINT ["dotnet", "Platinum.Service.UrlTaskInvoker.dll"]


